### ISSUE TITLE
Appointment Review 

### ISSUE THREAD

**Issue by EL1909** [EL1909/jhgeruetsbau#3]
As an Employee, I can see open appointments and it's details

## Acceptance Criteria:
- I can log in and see appointment requests made in the website by other visitors
- I can assign an appontment to an employee
- I can mark an appoinmnet as completed

## Tasks:
- [x] Create account app for employee's registration
- [x] TCreatte Termin app fr appontment administration
- [x] Enable functionallity using views and templates
